#!/bin/sh

mkdir -p "$SNAP_USER_COMMON"
cd "$SNAP_USER_COMMON"
if [ "$1" = "--version" ] || [ "$1" = "-V" ]; then
    echo "Frogtab Local $SNAP_VERSION"
elif [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    WORKING_ESCAPED="$(echo "$PWD" | sed 's/[\/&]/\\&/g')"
    echo "$("$SNAP/bin/frogtab" help)" | sed "s/the working directory/$WORKING_ESCAPED/g"
else
    FROGTAB_PORTS_FILE="$SNAP_COMMON/ports" "$SNAP/bin/frogtab" "$@"
fi