name: frogtab
version: 2.0.0b1snap4
title: Frogtab Local
summary: Run the Frogtab task manager on localhost
description: |
  Frogtab Local is a version of https://frogtab.com that you can run on your computer. With Frogab Local, you can:

    * Use Frogtab offline
    * Enable automatic backups in any browser
    * Send tasks to Frogtab via a terminal

  For a walkthrough of how to set up Frogtab Local on Ubuntu, see https://maybecoding.bearblog.dev/running-the-frogtab-task-manager-on-ubuntu/.


  **Starting Frogtab Local**

  To start Frogtab Local, run the following command:

  ```
  $ frogtab start
  ```

  Frogtab Local starts:

  ```
  ✓ Started Frogtab Local
  To access Frogtab, open http://127.0.0.1:5000 in your browser
  ```

  To change the port, first run `frogtab stop`. Then modify the `local_port` property in *~/snap/frogtab/common/config.py* and run `frogtab start` again.


  ** Sending tasks to Frogtab

  To send a task to Frogtab:

   1. Run the following command:

      ```
      $ frogtab
      ```

   2. Type the task, then press Enter. For example:

      ```
      Add a task to your inbox:
      > Record a demo video
      ✓ Sent task to Frogtab
      ```


  **Command reference**

  Here's the output of `frogtab help`:

  ```
  TODO
  ```


  **Release notes**

  https://github.com/dwilding/frogtab/releases


  **License**

  Frogtab Local is licensed under the MIT License.

  Frogtab Local uses OpenPGP.js for PGP encryption. The source code of OpenPGP.js is available at https://github.com/openpgpjs/openpgpjs. OpenPGP.js is licensed under the GNU Lesser General Public License.
grade: stable
confinement: strict
base: core24
apps:
  frogtab:
    command: bin/frogtab-wrapper
    plugs: [network-bind]
parts:
  python-environment:
    plugin: python
    source: .
    python-requirements: ['requirements.txt']
  source:
    plugin: dump
    source: .