name: frogtab
version: 1.08snap1
title: Frogtab Local
summary: Run the Frogtab task manager on localhost
description: |
  Frogtab Local is a version of https://frogtab.com that you can run on your computer. With Frogab Local, you can:

    * Use Frogtab offline
    * Enable automatic backups in any browser

  If you use Ubuntu, see https://maybecoding.bearblog.dev/running-the-frogtab-task-manager-on-ubuntu/ to learn how to set up Frogtab Local.

  **Running Frogtab Local**

  To run Frogtab Local, use the `frogtab` command.

  You should see the message `Running on http://127.0.0.1:5000`.
  You can ignore the warning about a development server.

  To access Frogtab, open http://127.0.0.1:5000 in your browser.

  To specify a different port, modify the `local_port` variable in _~/snap/frogtab/common/config.py_, then run `frogtab` again.

  **License**

  Frogtab Local is licensed under the MIT License.

  Frogtab Local uses OpenPGP.js for PGP encryption.
  The source code of OpenPGP.js is available at https://github.com/openpgpjs/openpgpjs.
  OpenPGP.js is licensed under the GNU Lesser General Public License.

  **Changelog**

  1.08snap1:

    * Sending tasks via a terminal now fails if the label has never been used by Frogtab

  1.07snap1:

    * You can now send tasks to Frogtab via a terminal, without registering for a personal link. See the help page

  1.06snap1:

    * You can now stop Frogtab Local via your browser. See the bottom of the help page
    * Reorganized the menu to always show Achievements. Removed Send to Frogtab from the menu
    * Reorganized the help page and explained Achievements in a more approachable way
    * Improved keyboard accessibility
    * Changed the ID format of generated key pairs, for better compatibility with GnuPG

  1.05snap1:

    * Added a variable in _config.py_ that specifies the server to use for personal links
    * Fixed a registration bug that occurred after importing an old backup file
grade: stable
confinement: strict
base: core24
apps:
  frogtab:
    command: bin/frogtab
    plugs: [network-bind]
parts:
  python-environment:
    plugin: python
    source: .
    python-requirements: ['flask/requirements.txt']
  source:
    plugin: dump
    source: .